In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr =np.array([1,4,5,7])
print(arr)
print(type(arr))


[1 4 5 7]
<class 'numpy.ndarray'>


In [11]:
print(arr[0]+arr[2])
print(arr[1:3])  #indexing[start:end] end-1
print(arr[0:3:2]) #indexing[start:end:step] step=1
print(arr[:4]) #last element

6
[4 5]
[1 5]
[1 4 5 7]


In [ ]:
arr=np.array(["h","i","$"])
arr.dtype  #tell datatype of array elements

dtype('<U1')

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('b')  #to convert from one datatype to another

print(newarr)
print(newarr.dtype)


[1 2 3]
int8


In [30]:
arr=np.array([1,3,45,6])
x= arr.copy()  #deep copy change in orignial array will not reflect in copied array
x[1]=90
y=arr.base
print(y)
print(arr)
print(x)

None
[ 1  3 45  6]
[ 1 90 45  6]


In [33]:
arr=np.array([1,3,5,7])
p=arr.view()  #shallow copy change in orignial array will reflect in copied array
p[0]=20
print(p.base)
print(arr)
print(p)

[20  3  5  7]
[20  3  5  7]
[20  3  5  7]


In [13]:
#shape of array tell deminsions of array and number of element present 
#reshape arrya
import numpy as np

A = np.array([[1, 2, 34, 3], [23, 89, 0, 23]])
B = np.array([1, 2, 3, 4], ndmin=3)
newarr = A.reshape(4,2)
print("Reshaped Array A to (4,2):",newarr)
newarr2 =B.reshape(1,2,2)
print("Reshaped Array B to (1,2,2):",newarr2)

print("Array A:")
print(A)
print("Shape of A:", A.shape)  # (2, 4)

print("\nArray B:")
print(B)
print("Shape of B:", B.shape)  # (1, 1, 4)


Reshaped Array A to (4,2): [[ 1  2]
 [34  3]
 [23 89]
 [ 0 23]]
Reshaped Array B to (1,2,2): [[[1 2]
  [3 4]]]
Array A:
[[ 1  2 34  3]
 [23 89  0 23]]
Shape of A: (2, 4)

Array B:
[[[1 2 3 4]]]
Shape of B: (1, 1, 4)


In [16]:
#iterating array
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
4
5
6
7


In [ ]:
#nditer() function iterate through every element of array
import numpy as np
arr = np.array([[[1,2],[2,3]]])
for x in np.nditer(arr[::2, ::2, ::2]):
    print(x)

1


In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [2]:
import numpy as np
arr =np.array([1,2,3,4,4])
arr2=np.array([5,8,9,9,0])
neww= arr+arr2
print(neww)

[ 6 10 12 13  4]


In [6]:
new = np.concatenate((arr,arr2),axis=0)
print(new)

[1 2 3 4 4 5 8 9 9 0]


In [15]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[7,8,9],[10,11,12]])
new = np.stack((arr,arr1),axis=0)
print(new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)
mul=arr1*arr2
print(mul)

print(arr)

[ 4 10 18]
[[1 2 3]
 [4 5 6]]


In [23]:
m=np.array([[[1,2],[90,4]],[[5,6],[78,8]]])
i=m.max()
i=m.min()
i=m.mean()
print("Mean:", m.mean())   # 24.25

m.sort()
print("Sorted array:\n", m)

Mean: 24.25
Sorted array:
 [[[ 1  2]
  [ 4 90]]

 [[ 5  6]
  [ 8 78]]]
