In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr =np.array([1,4,5,7])
print(arr)
print(type(arr))


[1 4 5 7]
<class 'numpy.ndarray'>


In [11]:
print(arr[0]+arr[2])
print(arr[1:3])  #indexing[start:end] end-1
print(arr[0:3:2]) #indexing[start:end:step] step=1
print(arr[:4]) #last element

6
[4 5]
[1 5]
[1 4 5 7]


In [ ]:
arr=np.array(["h","i","$"])
arr.dtype  #tell datatype of array elements

dtype('<U1')

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('b')  #to convert from one datatype to another

print(newarr)
print(newarr.dtype)


[1 2 3]
int8


In [30]:
arr=np.array([1,3,45,6])
x= arr.copy()  #deep copy change in orignial array will not reflect in copied array
x[1]=90
y=arr.base
print(y)
print(arr)
print(x)

None
[ 1  3 45  6]
[ 1 90 45  6]


In [33]:
arr=np.array([1,3,5,7])
p=arr.view()  #shallow copy change in orignial array will reflect in copied array
p[0]=20
print(p.base)
print(arr)
print(p)

[20  3  5  7]
[20  3  5  7]
[20  3  5  7]
